remote_theme: saifkhichi96/simple-material

title: Saif Khan
tagline: Mobile Developer and ML Engineer
baseurl: https://saifkhichi96.github.io
logo: /assets/images/logo.png

# page-specific customizations
categories: Machine Learning
demo: mSPeYTF9J4Q
